### Получение кол-ва оставшихся товаров на складеб на вход принимает название склада
POST http://localhost:8080/rpc
Content-Type: application/json

{
  "method": "Controller.Remainder",
  "params":[
    {"Name":"t1"}
  ],
  "id": 2
}

###  Резервирование товара на складе для доставки, на вход принимает массив из id товара и количество для резервации
POST http://localhost:8080/rpc
Content-Type: application/json

{
  "method": "Controller.Reservation",
  "params":[
    {"Products":[
      {"Id":"4795435a-a814-4203-8dc6-4bf093bec52e","Amount":3},
      {"Id":"4795435a-a814-4203-8dc6-4bf093bec52r","Amount":1}
    ]}
  ],
  "id": 1
}


###  Освобождение товара на складе для доставки, на вход принимает массив из id товара и количество для освобождения
POST http://localhost:8080/rpc
Content-Type: application/json

{
  "method": "Controller.Relief",
  "params":[
    {"Products":[
      {"Id":"4795435a-a814-4203-8dc6-4bf093bec52e","Amount":15},
      {"Id":"4795435a-a814-4203-8dc6-4bf093bec52r","Amount":1}
    ]}
  ],
  "id": 1
}

###

